// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4YicCo3QNGQBYz98llrZX5hcXi47Qny0',
    appId: '1:148215330977:web:36749e5df2edd2a3e318e0',
    messagingSenderId: '148215330977',
    projectId: 'signingappdemo',
    authDomain: 'signingappdemo.firebaseapp.com',
    storageBucket: 'signingappdemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhM6-nXHF3BtYPxZNz8lmGvp7t09CHmw',
    appId: '1:148215330977:android:ca005a02efc283f9e318e0',
    messagingSenderId: '148215330977',
    projectId: 'signingappdemo',
    storageBucket: 'signingappdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2F9NHkN00qmYDPwubMSxa1T31iFGWCDY',
    appId: '1:148215330977:ios:1b7425479989c891e318e0',
    messagingSenderId: '148215330977',
    projectId: 'signingappdemo',
    storageBucket: 'signingappdemo.appspot.com',
    androidClientId: '148215330977-j02mhefvj1ugenk6g2n3513dje7fmspu.apps.googleusercontent.com',
    iosClientId: '148215330977-mad9556d6dqs00890vb9rd5adgk7i9in.apps.googleusercontent.com',
    iosBundleId: 'com.example.citelis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2F9NHkN00qmYDPwubMSxa1T31iFGWCDY',
    appId: '1:148215330977:ios:1b7425479989c891e318e0',
    messagingSenderId: '148215330977',
    projectId: 'signingappdemo',
    storageBucket: 'signingappdemo.appspot.com',
    androidClientId: '148215330977-j02mhefvj1ugenk6g2n3513dje7fmspu.apps.googleusercontent.com',
    iosClientId: '148215330977-mad9556d6dqs00890vb9rd5adgk7i9in.apps.googleusercontent.com',
    iosBundleId: 'com.example.citelis',
  );
}
